/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_renlei_myapplication_jnindk_MainJni */
#include <stdio.h>
#ifndef _Included_com_example_renlei_myapplication_jnindk_MainJni
#define _Included_com_example_renlei_myapplication_jnindk_MainJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_renlei_myapplication_jnindk_MainJni
 * Method:    print
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_renlei_myapplication_jnindk_MainJni_print(JNIEnv *env, jobject obj, jstring ss){
    printf("%s","renlei");
}

#ifdef __cplusplus
}
#endif
#endif